export const QueryKeys = {
  AUTH_STATE: 'auth-state',
  CATEGORIES: 'categories',
  CATEGORIES_RESUME: 'categories-resume',
  CATEGORIES_DETAILS: 'categories-details',
  ACCOUNTS: 'accounts',
  BANKS: 'banks',
  TOTAL_BALANCES: 'total-balances',
  TRANSACTIONS: 'transactions',
  TOKENS: 'tokens',
  SHORTCUTS_CARDS: 'shortcuts-cards',
  SHORTCUTS_MERCHANTS: 'shortcuts-merchants',
  USERS_LIST: 'users-list',
  BALANCE_SUMMARY: 'balance-summary',
  DAILY_TOTAL: 'daily-totals',
} as const;
