/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as AuthenticatedRouteImport } from './routes/_authenticated';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard';
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index';
import { Route as AuthenticatedDashboardUsersRouteImport } from './routes/_authenticated/dashboard.users';
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings';

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedDashboardIndexRoute = AuthenticatedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedDashboardRoute,
} as any);
const AuthenticatedDashboardUsersRoute = AuthenticatedDashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedDashboardRoute,
} as any);
const AuthenticatedDashboardSettingsRoute = AuthenticatedDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedDashboardRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren;
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute;
  '/dashboard/users': typeof AuthenticatedDashboardUsersRoute;
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute;
  '/dashboard/users': typeof AuthenticatedDashboardUsersRoute;
  '/dashboard': typeof AuthenticatedDashboardIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_authenticated': typeof AuthenticatedRouteWithChildren;
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren;
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute;
  '/_authenticated/dashboard/users': typeof AuthenticatedDashboardUsersRoute;
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/dashboard' | '/dashboard/settings' | '/dashboard/users' | '/dashboard/';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/dashboard/settings' | '/dashboard/users' | '/dashboard';
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/users'
    | '/_authenticated/dashboard/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/';
      path: '/';
      fullPath: '/dashboard/';
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport;
      parentRoute: typeof AuthenticatedDashboardRoute;
    };
    '/_authenticated/dashboard/users': {
      id: '/_authenticated/dashboard/users';
      path: '/users';
      fullPath: '/dashboard/users';
      preLoaderRoute: typeof AuthenticatedDashboardUsersRouteImport;
      parentRoute: typeof AuthenticatedDashboardRoute;
    };
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings';
      path: '/settings';
      fullPath: '/dashboard/settings';
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport;
      parentRoute: typeof AuthenticatedDashboardRoute;
    };
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute;
  AuthenticatedDashboardUsersRoute: typeof AuthenticatedDashboardUsersRoute;
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute;
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren = {
  AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
  AuthenticatedDashboardUsersRoute: AuthenticatedDashboardUsersRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
};

const AuthenticatedDashboardRouteWithChildren = AuthenticatedDashboardRoute._addFileChildren(
  AuthenticatedDashboardRouteChildren
);

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
