/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardTransactionsRouteImport } from './routes/_authenticated/dashboard.transactions'
import { Route as AuthenticatedDashboardShortcutsRouteImport } from './routes/_authenticated/dashboard.shortcuts'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardCategoriesRouteImport } from './routes/_authenticated/dashboard.categories'
import { Route as AuthenticatedDashboardAccountsRouteImport } from './routes/_authenticated/dashboard.accounts'
import { Route as AuthenticatedDashboardAdminUsersRouteImport } from './routes/_authenticated/dashboard.admin/users'
import { Route as AuthenticatedDashboardAdminPageRouteImport } from './routes/_authenticated/dashboard.admin/page'
import { Route as AuthenticatedDashboardAdminMerchantsRouteImport } from './routes/_authenticated/dashboard.admin/merchants'
import { Route as AuthenticatedDashboardAdminBanksRouteImport } from './routes/_authenticated/dashboard.admin/banks'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTransactionsRoute =
  AuthenticatedDashboardTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardShortcutsRoute =
  AuthenticatedDashboardShortcutsRouteImport.update({
    id: '/shortcuts',
    path: '/shortcuts',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCategoriesRoute =
  AuthenticatedDashboardCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAccountsRoute =
  AuthenticatedDashboardAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminUsersRoute =
  AuthenticatedDashboardAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminPageRoute =
  AuthenticatedDashboardAdminPageRouteImport.update({
    id: '/admin/page',
    path: '/admin/page',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminMerchantsRoute =
  AuthenticatedDashboardAdminMerchantsRouteImport.update({
    id: '/admin/merchants',
    path: '/admin/merchants',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminBanksRoute =
  AuthenticatedDashboardAdminBanksRouteImport.update({
    id: '/admin/banks',
    path: '/admin/banks',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/accounts': typeof AuthenticatedDashboardAccountsRoute
  '/dashboard/categories': typeof AuthenticatedDashboardCategoriesRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/shortcuts': typeof AuthenticatedDashboardShortcutsRoute
  '/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admin/banks': typeof AuthenticatedDashboardAdminBanksRoute
  '/dashboard/admin/merchants': typeof AuthenticatedDashboardAdminMerchantsRoute
  '/dashboard/admin/page': typeof AuthenticatedDashboardAdminPageRoute
  '/dashboard/admin/users': typeof AuthenticatedDashboardAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/dashboard/accounts': typeof AuthenticatedDashboardAccountsRoute
  '/dashboard/categories': typeof AuthenticatedDashboardCategoriesRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/shortcuts': typeof AuthenticatedDashboardShortcutsRoute
  '/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admin/banks': typeof AuthenticatedDashboardAdminBanksRoute
  '/dashboard/admin/merchants': typeof AuthenticatedDashboardAdminMerchantsRoute
  '/dashboard/admin/page': typeof AuthenticatedDashboardAdminPageRoute
  '/dashboard/admin/users': typeof AuthenticatedDashboardAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/register': typeof RegisterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/accounts': typeof AuthenticatedDashboardAccountsRoute
  '/_authenticated/dashboard/categories': typeof AuthenticatedDashboardCategoriesRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/shortcuts': typeof AuthenticatedDashboardShortcutsRoute
  '/_authenticated/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/admin/banks': typeof AuthenticatedDashboardAdminBanksRoute
  '/_authenticated/dashboard/admin/merchants': typeof AuthenticatedDashboardAdminMerchantsRoute
  '/_authenticated/dashboard/admin/page': typeof AuthenticatedDashboardAdminPageRoute
  '/_authenticated/dashboard/admin/users': typeof AuthenticatedDashboardAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/dashboard'
    | '/dashboard/accounts'
    | '/dashboard/categories'
    | '/dashboard/settings'
    | '/dashboard/shortcuts'
    | '/dashboard/transactions'
    | '/dashboard/'
    | '/dashboard/admin/banks'
    | '/dashboard/admin/merchants'
    | '/dashboard/admin/page'
    | '/dashboard/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/dashboard/accounts'
    | '/dashboard/categories'
    | '/dashboard/settings'
    | '/dashboard/shortcuts'
    | '/dashboard/transactions'
    | '/dashboard'
    | '/dashboard/admin/banks'
    | '/dashboard/admin/merchants'
    | '/dashboard/admin/page'
    | '/dashboard/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/register'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/accounts'
    | '/_authenticated/dashboard/categories'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/shortcuts'
    | '/_authenticated/dashboard/transactions'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/admin/banks'
    | '/_authenticated/dashboard/admin/merchants'
    | '/_authenticated/dashboard/admin/page'
    | '/_authenticated/dashboard/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/transactions': {
      id: '/_authenticated/dashboard/transactions'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof AuthenticatedDashboardTransactionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/shortcuts': {
      id: '/_authenticated/dashboard/shortcuts'
      path: '/shortcuts'
      fullPath: '/dashboard/shortcuts'
      preLoaderRoute: typeof AuthenticatedDashboardShortcutsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/categories': {
      id: '/_authenticated/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof AuthenticatedDashboardCategoriesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/accounts': {
      id: '/_authenticated/dashboard/accounts'
      path: '/accounts'
      fullPath: '/dashboard/accounts'
      preLoaderRoute: typeof AuthenticatedDashboardAccountsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin/users': {
      id: '/_authenticated/dashboard/admin/users'
      path: '/admin/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof AuthenticatedDashboardAdminUsersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin/page': {
      id: '/_authenticated/dashboard/admin/page'
      path: '/admin/page'
      fullPath: '/dashboard/admin/page'
      preLoaderRoute: typeof AuthenticatedDashboardAdminPageRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin/merchants': {
      id: '/_authenticated/dashboard/admin/merchants'
      path: '/admin/merchants'
      fullPath: '/dashboard/admin/merchants'
      preLoaderRoute: typeof AuthenticatedDashboardAdminMerchantsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin/banks': {
      id: '/_authenticated/dashboard/admin/banks'
      path: '/admin/banks'
      fullPath: '/dashboard/admin/banks'
      preLoaderRoute: typeof AuthenticatedDashboardAdminBanksRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAccountsRoute: typeof AuthenticatedDashboardAccountsRoute
  AuthenticatedDashboardCategoriesRoute: typeof AuthenticatedDashboardCategoriesRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardShortcutsRoute: typeof AuthenticatedDashboardShortcutsRoute
  AuthenticatedDashboardTransactionsRoute: typeof AuthenticatedDashboardTransactionsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardAdminBanksRoute: typeof AuthenticatedDashboardAdminBanksRoute
  AuthenticatedDashboardAdminMerchantsRoute: typeof AuthenticatedDashboardAdminMerchantsRoute
  AuthenticatedDashboardAdminPageRoute: typeof AuthenticatedDashboardAdminPageRoute
  AuthenticatedDashboardAdminUsersRoute: typeof AuthenticatedDashboardAdminUsersRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAccountsRoute: AuthenticatedDashboardAccountsRoute,
    AuthenticatedDashboardCategoriesRoute:
      AuthenticatedDashboardCategoriesRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardShortcutsRoute: AuthenticatedDashboardShortcutsRoute,
    AuthenticatedDashboardTransactionsRoute:
      AuthenticatedDashboardTransactionsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardAdminBanksRoute:
      AuthenticatedDashboardAdminBanksRoute,
    AuthenticatedDashboardAdminMerchantsRoute:
      AuthenticatedDashboardAdminMerchantsRoute,
    AuthenticatedDashboardAdminPageRoute: AuthenticatedDashboardAdminPageRoute,
    AuthenticatedDashboardAdminUsersRoute:
      AuthenticatedDashboardAdminUsersRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
