/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardShortcutsRouteImport } from './routes/dashboard/shortcuts'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardAdminRouteRouteImport } from './routes/dashboard/admin/route'
import { Route as DashboardTransactionsIndexRouteImport } from './routes/dashboard/transactions/index'
import { Route as DashboardCategoriesIndexRouteImport } from './routes/dashboard/categories/index'
import { Route as DashboardAccountsIndexRouteImport } from './routes/dashboard/accounts/index'
import { Route as DashboardTransactionsNewRouteImport } from './routes/dashboard/transactions/new'
import { Route as DashboardCategoriesNewRouteImport } from './routes/dashboard/categories/new'
import { Route as DashboardCategoriesIdRouteImport } from './routes/dashboard/categories/$id'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard/admin/users'
import { Route as DashboardAdminMerchantsRouteImport } from './routes/dashboard/admin/merchants'
import { Route as DashboardAdminBanksRouteImport } from './routes/dashboard/admin/banks'
import { Route as DashboardAccountsNewRouteImport } from './routes/dashboard/accounts/new'
import { Route as DashboardTransactionsIdEditRouteImport } from './routes/dashboard/transactions/$id.edit'
import { Route as DashboardCategoriesIdEditRouteImport } from './routes/dashboard/categories/$id_.edit'
import { Route as DashboardAccountsIdEditRouteImport } from './routes/dashboard/accounts/$id.edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardShortcutsRoute = DashboardShortcutsRouteImport.update({
  id: '/shortcuts',
  path: '/shortcuts',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminRouteRoute = DashboardAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTransactionsIndexRoute =
  DashboardTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCategoriesIndexRoute =
  DashboardCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountsIndexRoute = DashboardAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTransactionsNewRoute =
  DashboardTransactionsNewRouteImport.update({
    id: '/transactions/new',
    path: '/transactions/new',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCategoriesNewRoute = DashboardCategoriesNewRouteImport.update({
  id: '/categories/new',
  path: '/categories/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCategoriesIdRoute = DashboardCategoriesIdRouteImport.update({
  id: '/categories/$id',
  path: '/categories/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const DashboardAdminMerchantsRoute = DashboardAdminMerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const DashboardAdminBanksRoute = DashboardAdminBanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const DashboardAccountsNewRoute = DashboardAccountsNewRouteImport.update({
  id: '/accounts/new',
  path: '/accounts/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTransactionsIdEditRoute =
  DashboardTransactionsIdEditRouteImport.update({
    id: '/transactions/$id/edit',
    path: '/transactions/$id/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCategoriesIdEditRoute =
  DashboardCategoriesIdEditRouteImport.update({
    id: '/categories/$id_/edit',
    path: '/categories/$id/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountsIdEditRoute = DashboardAccountsIdEditRouteImport.update({
  id: '/accounts/$id/edit',
  path: '/accounts/$id/edit',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/shortcuts': typeof DashboardShortcutsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/accounts/new': typeof DashboardAccountsNewRoute
  '/dashboard/admin/banks': typeof DashboardAdminBanksRoute
  '/dashboard/admin/merchants': typeof DashboardAdminMerchantsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/categories/$id': typeof DashboardCategoriesIdRoute
  '/dashboard/categories/new': typeof DashboardCategoriesNewRoute
  '/dashboard/transactions/new': typeof DashboardTransactionsNewRoute
  '/dashboard/accounts': typeof DashboardAccountsIndexRoute
  '/dashboard/categories': typeof DashboardCategoriesIndexRoute
  '/dashboard/transactions': typeof DashboardTransactionsIndexRoute
  '/dashboard/accounts/$id/edit': typeof DashboardAccountsIdEditRoute
  '/dashboard/categories/$id/edit': typeof DashboardCategoriesIdEditRoute
  '/dashboard/transactions/$id/edit': typeof DashboardTransactionsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/shortcuts': typeof DashboardShortcutsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/accounts/new': typeof DashboardAccountsNewRoute
  '/dashboard/admin/banks': typeof DashboardAdminBanksRoute
  '/dashboard/admin/merchants': typeof DashboardAdminMerchantsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/categories/$id': typeof DashboardCategoriesIdRoute
  '/dashboard/categories/new': typeof DashboardCategoriesNewRoute
  '/dashboard/transactions/new': typeof DashboardTransactionsNewRoute
  '/dashboard/accounts': typeof DashboardAccountsIndexRoute
  '/dashboard/categories': typeof DashboardCategoriesIndexRoute
  '/dashboard/transactions': typeof DashboardTransactionsIndexRoute
  '/dashboard/accounts/$id/edit': typeof DashboardAccountsIdEditRoute
  '/dashboard/categories/$id/edit': typeof DashboardCategoriesIdEditRoute
  '/dashboard/transactions/$id/edit': typeof DashboardTransactionsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/shortcuts': typeof DashboardShortcutsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/accounts/new': typeof DashboardAccountsNewRoute
  '/dashboard/admin/banks': typeof DashboardAdminBanksRoute
  '/dashboard/admin/merchants': typeof DashboardAdminMerchantsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/categories/$id': typeof DashboardCategoriesIdRoute
  '/dashboard/categories/new': typeof DashboardCategoriesNewRoute
  '/dashboard/transactions/new': typeof DashboardTransactionsNewRoute
  '/dashboard/accounts/': typeof DashboardAccountsIndexRoute
  '/dashboard/categories/': typeof DashboardCategoriesIndexRoute
  '/dashboard/transactions/': typeof DashboardTransactionsIndexRoute
  '/dashboard/accounts/$id/edit': typeof DashboardAccountsIdEditRoute
  '/dashboard/categories/$id_/edit': typeof DashboardCategoriesIdEditRoute
  '/dashboard/transactions/$id/edit': typeof DashboardTransactionsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/dashboard/admin'
    | '/dashboard/settings'
    | '/dashboard/shortcuts'
    | '/dashboard/'
    | '/dashboard/accounts/new'
    | '/dashboard/admin/banks'
    | '/dashboard/admin/merchants'
    | '/dashboard/admin/users'
    | '/dashboard/categories/$id'
    | '/dashboard/categories/new'
    | '/dashboard/transactions/new'
    | '/dashboard/accounts'
    | '/dashboard/categories'
    | '/dashboard/transactions'
    | '/dashboard/accounts/$id/edit'
    | '/dashboard/categories/$id/edit'
    | '/dashboard/transactions/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/dashboard/admin'
    | '/dashboard/settings'
    | '/dashboard/shortcuts'
    | '/dashboard'
    | '/dashboard/accounts/new'
    | '/dashboard/admin/banks'
    | '/dashboard/admin/merchants'
    | '/dashboard/admin/users'
    | '/dashboard/categories/$id'
    | '/dashboard/categories/new'
    | '/dashboard/transactions/new'
    | '/dashboard/accounts'
    | '/dashboard/categories'
    | '/dashboard/transactions'
    | '/dashboard/accounts/$id/edit'
    | '/dashboard/categories/$id/edit'
    | '/dashboard/transactions/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/dashboard/admin'
    | '/dashboard/settings'
    | '/dashboard/shortcuts'
    | '/dashboard/'
    | '/dashboard/accounts/new'
    | '/dashboard/admin/banks'
    | '/dashboard/admin/merchants'
    | '/dashboard/admin/users'
    | '/dashboard/categories/$id'
    | '/dashboard/categories/new'
    | '/dashboard/transactions/new'
    | '/dashboard/accounts/'
    | '/dashboard/categories/'
    | '/dashboard/transactions/'
    | '/dashboard/accounts/$id/edit'
    | '/dashboard/categories/$id_/edit'
    | '/dashboard/transactions/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/shortcuts': {
      id: '/dashboard/shortcuts'
      path: '/shortcuts'
      fullPath: '/dashboard/shortcuts'
      preLoaderRoute: typeof DashboardShortcutsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/transactions/': {
      id: '/dashboard/transactions/'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof DashboardTransactionsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/categories/': {
      id: '/dashboard/categories/'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof DashboardCategoriesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accounts/': {
      id: '/dashboard/accounts/'
      path: '/accounts'
      fullPath: '/dashboard/accounts'
      preLoaderRoute: typeof DashboardAccountsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/transactions/new': {
      id: '/dashboard/transactions/new'
      path: '/transactions/new'
      fullPath: '/dashboard/transactions/new'
      preLoaderRoute: typeof DashboardTransactionsNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/categories/new': {
      id: '/dashboard/categories/new'
      path: '/categories/new'
      fullPath: '/dashboard/categories/new'
      preLoaderRoute: typeof DashboardCategoriesNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/categories/$id': {
      id: '/dashboard/categories/$id'
      path: '/categories/$id'
      fullPath: '/dashboard/categories/$id'
      preLoaderRoute: typeof DashboardCategoriesIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/merchants': {
      id: '/dashboard/admin/merchants'
      path: '/merchants'
      fullPath: '/dashboard/admin/merchants'
      preLoaderRoute: typeof DashboardAdminMerchantsRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/banks': {
      id: '/dashboard/admin/banks'
      path: '/banks'
      fullPath: '/dashboard/admin/banks'
      preLoaderRoute: typeof DashboardAdminBanksRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/accounts/new': {
      id: '/dashboard/accounts/new'
      path: '/accounts/new'
      fullPath: '/dashboard/accounts/new'
      preLoaderRoute: typeof DashboardAccountsNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/transactions/$id/edit': {
      id: '/dashboard/transactions/$id/edit'
      path: '/transactions/$id/edit'
      fullPath: '/dashboard/transactions/$id/edit'
      preLoaderRoute: typeof DashboardTransactionsIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/categories/$id_/edit': {
      id: '/dashboard/categories/$id_/edit'
      path: '/categories/$id/edit'
      fullPath: '/dashboard/categories/$id/edit'
      preLoaderRoute: typeof DashboardCategoriesIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accounts/$id/edit': {
      id: '/dashboard/accounts/$id/edit'
      path: '/accounts/$id/edit'
      fullPath: '/dashboard/accounts/$id/edit'
      preLoaderRoute: typeof DashboardAccountsIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardAdminRouteRouteChildren {
  DashboardAdminBanksRoute: typeof DashboardAdminBanksRoute
  DashboardAdminMerchantsRoute: typeof DashboardAdminMerchantsRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
}

const DashboardAdminRouteRouteChildren: DashboardAdminRouteRouteChildren = {
  DashboardAdminBanksRoute: DashboardAdminBanksRoute,
  DashboardAdminMerchantsRoute: DashboardAdminMerchantsRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
}

const DashboardAdminRouteRouteWithChildren =
  DashboardAdminRouteRoute._addFileChildren(DashboardAdminRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAdminRouteRoute: typeof DashboardAdminRouteRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardShortcutsRoute: typeof DashboardShortcutsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAccountsNewRoute: typeof DashboardAccountsNewRoute
  DashboardCategoriesIdRoute: typeof DashboardCategoriesIdRoute
  DashboardCategoriesNewRoute: typeof DashboardCategoriesNewRoute
  DashboardTransactionsNewRoute: typeof DashboardTransactionsNewRoute
  DashboardAccountsIndexRoute: typeof DashboardAccountsIndexRoute
  DashboardCategoriesIndexRoute: typeof DashboardCategoriesIndexRoute
  DashboardTransactionsIndexRoute: typeof DashboardTransactionsIndexRoute
  DashboardAccountsIdEditRoute: typeof DashboardAccountsIdEditRoute
  DashboardCategoriesIdEditRoute: typeof DashboardCategoriesIdEditRoute
  DashboardTransactionsIdEditRoute: typeof DashboardTransactionsIdEditRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAdminRouteRoute: DashboardAdminRouteRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardShortcutsRoute: DashboardShortcutsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAccountsNewRoute: DashboardAccountsNewRoute,
  DashboardCategoriesIdRoute: DashboardCategoriesIdRoute,
  DashboardCategoriesNewRoute: DashboardCategoriesNewRoute,
  DashboardTransactionsNewRoute: DashboardTransactionsNewRoute,
  DashboardAccountsIndexRoute: DashboardAccountsIndexRoute,
  DashboardCategoriesIndexRoute: DashboardCategoriesIndexRoute,
  DashboardTransactionsIndexRoute: DashboardTransactionsIndexRoute,
  DashboardAccountsIdEditRoute: DashboardAccountsIdEditRoute,
  DashboardCategoriesIdEditRoute: DashboardCategoriesIdEditRoute,
  DashboardTransactionsIdEditRoute: DashboardTransactionsIdEditRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
